### PR TITLE
Extending supported eta range for jets to 4.5

### PR DESCRIPTION
**Pull request by TomasDado**
We plan to have support for TF for jets to up to eta 4.5. Adjusting the detector class so it can use them.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by TomasDado** [comment]
Indeed, there is a problem when not all of the eta regions for one set are present. But this is a general problem, not related to this specific PR.

**Comment by knutzk** [comment]
Ok, thanks for investigating. I think this is a problem that should be addressed though ... Especially when extending the functionality of the detector classes, there will be parameter sets without support for the full eta range. We need to make sure that the requirements and availabilities are checked correctly.

**Comment by TomasDado** [comment]
Sure it should be fixed, but I would suggest to open a new PR for that fix

**Comment by knutzk** [comment]
Ok, that's fine with me. In that case we should at least open an issue to keep track of it.

**Pull request merged**
