### PR TITLE
Introduce smart pointers in class Particles

### PR DESCRIPTION
**Pull request by knutzk**
## Description

This PR removes raw pointers from & introduces smart pointers to the class `Particles`. In particular, this class contained lots of pointers to containers, that had to be initialised in the constructor, and deleted in the destructor. Pointers there were unnecessary, so they were removed. 

A lot of these containers had, in addition, entries of pointer types, e.g. `std::vector<TLorentzVector*>*`. This made their handling a little more complicated than necessary. To avoid the necessary inclusion of the TLorentzVector class, these raw pointers were _not_ converted into objects types, but into smart pointers. That is, those containers now became `std::vector<std::unique_ptr<TLorentzVector>>`. This will allow forward declarations of the TLorentzVector class, which will be addressed in another PR.

With the switch from pointers to objects, and from raw to smart pointers, a lot of minor syntax changes throughout the class were necessary. In particular, it was necessary to adjust the method
```diff
-  std::vector <TLorentzVector *> * ParticleContainer(KLFitter::Particles::ParticleType ptype);
+  std::vector<std::unique_ptr<TLorentzVector> >* ParticleContainer(KLFitter::Particles::ParticleType ptype);
```

## Related Issue

#16 (removal of raw pointers)
#21 (reduction of ROOT dependencies/includes)

## Motivation and Context

This clarifies a lot of the syntax; constructor and destructor implementations became unnecessary. In addition, memory is handled automatically, no `delete` commands necessary anywhere anymore.

## How Has This Been Tested?

The code was compiled and tested with the included unit tests and the example file. The behaviour is identical to what it was before. Valgrind was used to check for potential memory leaks. Here are the outputs before and after the changes:
```
==23239== LEAK SUMMARY:
==23239==    definitely lost: 144 bytes in 6 blocks
==23239==    indirectly lost: 168 bytes in 6 blocks
==23239==      possibly lost: 114,840 bytes in 883 blocks
==23239==    still reachable: 61,833,697 bytes in 98,383 blocks
==23239==         suppressed: 0 bytes in 0 blocks
```
```
==22560== LEAK SUMMARY:
==22560==    definitely lost: 144 bytes in 6 blocks
==22560==    indirectly lost: 168 bytes in 6 blocks
==22560==      possibly lost: 115,376 bytes in 890 blocks
==22560==    still reachable: 61,833,161 bytes in 98,376 blocks
==22560==         suppressed: 0 bytes in 0 blocks
```
All reported losses (definitely, indirectly, possibly) are due to cling/ROOT ... 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by knutzk** [comment]
/cc @TomasDado @johanneserdmann @nackenho 

I just wanted to check whether you are fine with these changes. I think they significantly improve readability (also by removing ~150 lines from just one class), and automated memory management is definitely something we should aim for. If you are fine with them, I will start doing the same in the other classes, too. I've only done it for one for now, because lots of small syntax changes are necessary and it's probably easier to review it bit by bit.

**Comment by TomasDado** [comment]
Hi @knutzk,

of course I am fine with that, but it will require lot of work.

**Comment by knutzk** [comment]
@TomasDado, agreed, it will be a bit of work. But I'd be happy to do it 😉

**Comment by knutzk** [comment]
Merging this now ... Worst case: there's always the option to revert.

**Comment by nackenho** [comment]
@knutzk : In principle, I agree with these changes. This pointer business can get messy, in particular if the classes become more complicated and making sure there are no memory leaks is not always trivial. However, they also do have their advantages and we mainly followed Kevin's lead, when writing/extending the classes. To really do this consistently will be also quite some (boring) work.

**Comment by knutzk** [comment]
@nackenho, thanks for the feedback! Yes, it's a lot of boring work, I'll do it step by step. But I disagree with your other statement: I don't see any advantages of raw pointers and manual memory management ... I'd say we should introduce this step by step everywhere and then stick to it, also to avoid things like #17 and #18.

**Pull request merged**
